import type { FigureClassificationQuestion, ShapeConfig } from '../../lib/types';

export const figureClassificationQuestions: FigureClassificationQuestion[] = [
  // ============================================================
  // EASY QUESTIONS (fc-e-1 through fc-e-20)
  // ============================================================

  // --- Same number of sides (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-e-1',
    difficulty: 'easy',
    rule: 'All figures are triangles (3 sides)',
    figures: [
      { shapeType: 'triangle', fill: 'solid', size: 'large' },
      { shapeType: 'triangle', fill: 'empty', size: 'small' },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'medium' },
    ],
    choices: [
      { shapeType: 'square', fill: 'solid', size: 'medium' },
      { shapeType: 'triangle', fill: 'dotted', size: 'medium' },
      { shapeType: 'circle', fill: 'empty', size: 'large' },
      { shapeType: 'pentagon', fill: 'solid', size: 'small' },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'medium' },
    ],
    correctAnswer: 1,
    explanation: 'All three figures are triangles. Only choice B is also a triangle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-2',
    difficulty: 'easy',
    rule: 'All figures are squares (4 sides)',
    figures: [
      { shapeType: 'square', fill: 'empty', size: 'small' },
      { shapeType: 'square', fill: 'solid', size: 'large' },
      { shapeType: 'square', fill: 'striped-vertical', size: 'medium' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'solid', size: 'medium' },
      { shapeType: 'circle', fill: 'empty', size: 'small' },
      { shapeType: 'hexagon', fill: 'striped-vertical', size: 'medium' },
      { shapeType: 'square', fill: 'dotted', size: 'large' },
      { shapeType: 'pentagon', fill: 'solid', size: 'large' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures are squares. Only choice D is also a square.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-3',
    difficulty: 'easy',
    rule: 'All figures are pentagons (5 sides)',
    figures: [
      { shapeType: 'pentagon', fill: 'solid', size: 'medium' },
      { shapeType: 'pentagon', fill: 'empty', size: 'large' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'small' },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'solid', size: 'medium' },
      { shapeType: 'triangle', fill: 'dotted', size: 'small' },
      { shapeType: 'square', fill: 'empty', size: 'large' },
      { shapeType: 'star', fill: 'solid', size: 'medium' },
      { shapeType: 'pentagon', fill: 'striped-horizontal', size: 'medium' },
    ],
    correctAnswer: 4,
    explanation: 'All three figures are pentagons. Only choice E is also a pentagon.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-4',
    difficulty: 'easy',
    rule: 'All figures are hexagons (6 sides)',
    figures: [
      { shapeType: 'hexagon', fill: 'striped-diagonal', size: 'large' },
      { shapeType: 'hexagon', fill: 'solid', size: 'small' },
      { shapeType: 'hexagon', fill: 'empty', size: 'medium' },
    ],
    choices: [
      { shapeType: 'pentagon', fill: 'striped-diagonal', size: 'large' },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'square', fill: 'empty', size: 'medium' },
      { shapeType: 'diamond', fill: 'solid', size: 'large' },
    ],
    correctAnswer: 1,
    explanation: 'All three figures are hexagons. Only choice B is also a hexagon.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-5',
    difficulty: 'easy',
    rule: 'All figures have 4 sides (squares and diamonds)',
    figures: [
      { shapeType: 'square', fill: 'solid', size: 'medium' },
      { shapeType: 'diamond', fill: 'empty', size: 'large' },
      { shapeType: 'square', fill: 'striped-horizontal', size: 'small' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'solid', size: 'medium' },
      { shapeType: 'circle', fill: 'empty', size: 'large' },
      { shapeType: 'pentagon', fill: 'striped-horizontal', size: 'small' },
      { shapeType: 'diamond', fill: 'dotted', size: 'medium' },
      { shapeType: 'hexagon', fill: 'solid', size: 'large' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures have 4 sides (squares and diamonds are both quadrilaterals). Choice D is a diamond, which also has 4 sides.',
  },

  // --- Same fill type (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-e-6',
    difficulty: 'easy',
    rule: 'All figures are solid (filled)',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'large' },
      { shapeType: 'triangle', fill: 'solid', size: 'small' },
      { shapeType: 'hexagon', fill: 'solid', size: 'medium' },
    ],
    choices: [
      { shapeType: 'square', fill: 'empty', size: 'medium' },
      { shapeType: 'pentagon', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'star', fill: 'solid', size: 'small' },
      { shapeType: 'diamond', fill: 'dotted', size: 'medium' },
      { shapeType: 'arrow', fill: 'striped-vertical', size: 'large' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures have a solid fill. Only choice C also has a solid fill.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-7',
    difficulty: 'easy',
    rule: 'All figures are empty (outline only)',
    figures: [
      { shapeType: 'square', fill: 'empty', size: 'medium' },
      { shapeType: 'star', fill: 'empty', size: 'large' },
      { shapeType: 'pentagon', fill: 'empty', size: 'small' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'solid', size: 'medium' },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'triangle', fill: 'dotted', size: 'small' },
      { shapeType: 'diamond', fill: 'striped-diagonal', size: 'medium' },
      { shapeType: 'arrow', fill: 'empty', size: 'large' },
    ],
    correctAnswer: 4,
    explanation: 'All three figures are empty (outline only). Only choice E is also empty.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-8',
    difficulty: 'easy',
    rule: 'All figures have horizontal stripes',
    figures: [
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'diamond', fill: 'striped-horizontal', size: 'small' },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'square', fill: 'solid', size: 'large' },
      { shapeType: 'star', fill: 'striped-vertical', size: 'small' },
      { shapeType: 'pentagon', fill: 'empty', size: 'medium' },
      { shapeType: 'arrow', fill: 'dotted', size: 'large' },
    ],
    correctAnswer: 0,
    explanation: 'All three figures have horizontal stripes. Only choice A also has horizontal stripes.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-9',
    difficulty: 'easy',
    rule: 'All figures are dotted',
    figures: [
      { shapeType: 'pentagon', fill: 'dotted', size: 'small' },
      { shapeType: 'square', fill: 'dotted', size: 'large' },
      { shapeType: 'star', fill: 'dotted', size: 'medium' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'triangle', fill: 'empty', size: 'large' },
      { shapeType: 'hexagon', fill: 'striped-diagonal', size: 'medium' },
      { shapeType: 'arrow', fill: 'striped-horizontal', size: 'small' },
      { shapeType: 'diamond', fill: 'dotted', size: 'large' },
    ],
    correctAnswer: 4,
    explanation: 'All three figures are dotted. Only choice E is also dotted.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-10',
    difficulty: 'easy',
    rule: 'All figures have vertical stripes',
    figures: [
      { shapeType: 'hexagon', fill: 'striped-vertical', size: 'large' },
      { shapeType: 'arrow', fill: 'striped-vertical', size: 'medium' },
      { shapeType: 'square', fill: 'striped-vertical', size: 'small' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'triangle', fill: 'solid', size: 'large' },
      { shapeType: 'pentagon', fill: 'striped-vertical', size: 'medium' },
      { shapeType: 'star', fill: 'empty', size: 'small' },
      { shapeType: 'diamond', fill: 'dotted', size: 'large' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures have vertical stripes. Only choice C also has vertical stripes.',
  },

  // --- Same shape type (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-e-11',
    difficulty: 'easy',
    rule: 'All figures are circles',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'circle', fill: 'empty', size: 'large' },
      { shapeType: 'circle', fill: 'dotted', size: 'medium' },
    ],
    choices: [
      { shapeType: 'square', fill: 'solid', size: 'small' },
      { shapeType: 'triangle', fill: 'empty', size: 'large' },
      { shapeType: 'circle', fill: 'striped-diagonal', size: 'medium' },
      { shapeType: 'hexagon', fill: 'dotted', size: 'small' },
      { shapeType: 'pentagon', fill: 'solid', size: 'large' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are circles. Only choice C is also a circle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-12',
    difficulty: 'easy',
    rule: 'All figures are stars',
    figures: [
      { shapeType: 'star', fill: 'empty', size: 'large' },
      { shapeType: 'star', fill: 'solid', size: 'medium' },
      { shapeType: 'star', fill: 'striped-horizontal', size: 'small' },
    ],
    choices: [
      { shapeType: 'cross', fill: 'empty', size: 'large' },
      { shapeType: 'diamond', fill: 'solid', size: 'medium' },
      { shapeType: 'arrow', fill: 'striped-horizontal', size: 'small' },
      { shapeType: 'hexagon', fill: 'solid', size: 'large' },
      { shapeType: 'star', fill: 'dotted', size: 'medium' },
    ],
    correctAnswer: 4,
    explanation: 'All three figures are stars. Only choice E is also a star.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-13',
    difficulty: 'easy',
    rule: 'All figures are arrows',
    figures: [
      { shapeType: 'arrow', fill: 'solid', size: 'medium' },
      { shapeType: 'arrow', fill: 'striped-vertical', size: 'large' },
      { shapeType: 'arrow', fill: 'empty', size: 'small' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'solid', size: 'medium' },
      { shapeType: 'arrow', fill: 'striped-diagonal', size: 'large' },
      { shapeType: 'star', fill: 'empty', size: 'small' },
      { shapeType: 'cross', fill: 'solid', size: 'medium' },
      { shapeType: 'diamond', fill: 'striped-vertical', size: 'large' },
    ],
    correctAnswer: 1,
    explanation: 'All three figures are arrows. Only choice B is also an arrow.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-14',
    difficulty: 'easy',
    rule: 'All figures are diamonds',
    figures: [
      { shapeType: 'diamond', fill: 'dotted', size: 'large' },
      { shapeType: 'diamond', fill: 'solid', size: 'small' },
      { shapeType: 'diamond', fill: 'striped-horizontal', size: 'medium' },
    ],
    choices: [
      { shapeType: 'diamond', fill: 'empty', size: 'medium' },
      { shapeType: 'square', fill: 'dotted', size: 'large' },
      { shapeType: 'hexagon', fill: 'solid', size: 'small' },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'circle', fill: 'solid', size: 'large' },
    ],
    correctAnswer: 0,
    explanation: 'All three figures are diamonds. Only choice A is also a diamond.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-15',
    difficulty: 'easy',
    rule: 'All figures are crosses',
    figures: [
      { shapeType: 'cross', fill: 'solid', size: 'large' },
      { shapeType: 'cross', fill: 'empty', size: 'medium' },
      { shapeType: 'cross', fill: 'striped-vertical', size: 'small' },
    ],
    choices: [
      { shapeType: 'star', fill: 'solid', size: 'large' },
      { shapeType: 'arrow', fill: 'empty', size: 'medium' },
      { shapeType: 'triangle', fill: 'striped-vertical', size: 'small' },
      { shapeType: 'cross', fill: 'dotted', size: 'medium' },
      { shapeType: 'square', fill: 'solid', size: 'large' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures are crosses. Only choice D is also a cross.',
  },

  // --- Same size (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-e-16',
    difficulty: 'easy',
    rule: 'All figures are small',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'triangle', fill: 'empty', size: 'small' },
      { shapeType: 'hexagon', fill: 'dotted', size: 'small' },
    ],
    choices: [
      { shapeType: 'square', fill: 'solid', size: 'large' },
      { shapeType: 'pentagon', fill: 'empty', size: 'medium' },
      { shapeType: 'star', fill: 'dotted', size: 'small' },
      { shapeType: 'diamond', fill: 'solid', size: 'large' },
      { shapeType: 'arrow', fill: 'empty', size: 'medium' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are small. Only choice C is also small.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-17',
    difficulty: 'easy',
    rule: 'All figures are medium',
    figures: [
      { shapeType: 'square', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'star', fill: 'solid', size: 'medium' },
      { shapeType: 'diamond', fill: 'empty', size: 'medium' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'triangle', fill: 'solid', size: 'small' },
      { shapeType: 'hexagon', fill: 'empty', size: 'medium' },
      { shapeType: 'pentagon', fill: 'solid', size: 'large' },
      { shapeType: 'arrow', fill: 'dotted', size: 'small' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are medium-sized. Only choice C is also medium.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-18',
    difficulty: 'easy',
    rule: 'All figures are large',
    figures: [
      { shapeType: 'pentagon', fill: 'solid', size: 'large' },
      { shapeType: 'arrow', fill: 'empty', size: 'large' },
      { shapeType: 'cross', fill: 'dotted', size: 'large' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'triangle', fill: 'empty', size: 'medium' },
      { shapeType: 'square', fill: 'dotted', size: 'small' },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'diamond', fill: 'solid', size: 'medium' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures are large. Only choice D is also large.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-19',
    difficulty: 'easy',
    rule: 'All figures are small circles (same shape and size)',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'circle', fill: 'empty', size: 'small' },
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'small' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'dotted', size: 'large' },
      { shapeType: 'triangle', fill: 'solid', size: 'small' },
      { shapeType: 'circle', fill: 'striped-vertical', size: 'small' },
      { shapeType: 'square', fill: 'empty', size: 'small' },
      { shapeType: 'circle', fill: 'solid', size: 'medium' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are small circles. Choice C is the only small circle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-e-20',
    difficulty: 'easy',
    rule: 'All figures are large triangles',
    figures: [
      { shapeType: 'triangle', fill: 'solid', size: 'large' },
      { shapeType: 'triangle', fill: 'dotted', size: 'large' },
      { shapeType: 'triangle', fill: 'empty', size: 'large' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'small' },
      { shapeType: 'square', fill: 'solid', size: 'large' },
      { shapeType: 'triangle', fill: 'striped-vertical', size: 'large' },
      { shapeType: 'hexagon', fill: 'empty', size: 'large' },
      { shapeType: 'triangle', fill: 'solid', size: 'medium' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are large triangles. Choice C is the only large triangle.',
  },

  // ============================================================
  // MEDIUM QUESTIONS (fc-m-1 through fc-m-20)
  // ============================================================

  // --- Same inner shape (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-m-1',
    difficulty: 'medium',
    rule: 'All figures contain an inner circle',
    figures: [
      { shapeType: 'square', fill: 'empty', size: 'large', innerShape: 'circle' },
      { shapeType: 'triangle', fill: 'solid', size: 'medium', innerShape: 'circle' },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'large', innerShape: 'circle' },
    ],
    choices: [
      { shapeType: 'pentagon', fill: 'empty', size: 'large', innerShape: 'triangle' },
      { shapeType: 'diamond', fill: 'solid', size: 'medium', innerShape: 'circle' },
      { shapeType: 'star', fill: 'empty', size: 'large', innerShape: 'square' },
      { shapeType: 'circle', fill: 'solid', size: 'medium', innerShape: 'dot' },
      { shapeType: 'arrow', fill: 'striped-horizontal', size: 'large', innerShape: 'none' },
    ],
    correctAnswer: 1,
    explanation: 'All three figures contain an inner circle. Only choice B also has an inner circle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-2',
    difficulty: 'medium',
    rule: 'All figures contain an inner dot',
    figures: [
      { shapeType: 'circle', fill: 'empty', size: 'large', innerShape: 'dot' },
      { shapeType: 'square', fill: 'empty', size: 'medium', innerShape: 'dot' },
      { shapeType: 'pentagon', fill: 'empty', size: 'small', innerShape: 'dot' },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'empty', size: 'large', innerShape: 'circle' },
      { shapeType: 'triangle', fill: 'empty', size: 'medium', innerShape: 'none' },
      { shapeType: 'star', fill: 'empty', size: 'small', innerShape: 'triangle' },
      { shapeType: 'diamond', fill: 'empty', size: 'medium', innerShape: 'dot' },
      { shapeType: 'arrow', fill: 'empty', size: 'large', innerShape: 'square' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures contain an inner dot. Only choice D also has an inner dot.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-3',
    difficulty: 'medium',
    rule: 'All figures contain an inner triangle',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'large', innerShape: 'triangle' },
      { shapeType: 'hexagon', fill: 'empty', size: 'medium', innerShape: 'triangle' },
      { shapeType: 'square', fill: 'dotted', size: 'large', innerShape: 'triangle' },
    ],
    choices: [
      { shapeType: 'pentagon', fill: 'solid', size: 'large', innerShape: 'circle' },
      { shapeType: 'diamond', fill: 'empty', size: 'medium', innerShape: 'dot' },
      { shapeType: 'triangle', fill: 'dotted', size: 'large', innerShape: 'triangle' },
      { shapeType: 'star', fill: 'solid', size: 'medium', innerShape: 'square' },
      { shapeType: 'cross', fill: 'empty', size: 'small', innerShape: 'none' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures contain an inner triangle. Only choice C also has an inner triangle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-4',
    difficulty: 'medium',
    rule: 'All figures contain an inner square',
    figures: [
      { shapeType: 'circle', fill: 'empty', size: 'large', innerShape: 'square' },
      { shapeType: 'pentagon', fill: 'solid', size: 'medium', innerShape: 'square' },
      { shapeType: 'hexagon', fill: 'striped-vertical', size: 'large', innerShape: 'square' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'empty', size: 'large', innerShape: 'circle' },
      { shapeType: 'square', fill: 'solid', size: 'medium', innerShape: 'dot' },
      { shapeType: 'diamond', fill: 'striped-vertical', size: 'large', innerShape: 'triangle' },
      { shapeType: 'star', fill: 'empty', size: 'medium', innerShape: 'none' },
      { shapeType: 'arrow', fill: 'solid', size: 'large', innerShape: 'square' },
    ],
    correctAnswer: 4,
    explanation: 'All three figures contain an inner square. Only choice E also has an inner square.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-5',
    difficulty: 'medium',
    rule: 'All figures have no inner shape',
    figures: [
      { shapeType: 'star', fill: 'solid', size: 'medium', innerShape: 'none' },
      { shapeType: 'diamond', fill: 'empty', size: 'large', innerShape: 'none' },
      { shapeType: 'cross', fill: 'dotted', size: 'small', innerShape: 'none' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'solid', size: 'medium', innerShape: 'dot' },
      { shapeType: 'triangle', fill: 'empty', size: 'large', innerShape: 'circle' },
      { shapeType: 'hexagon', fill: 'dotted', size: 'small', innerShape: 'none' },
      { shapeType: 'square', fill: 'solid', size: 'medium', innerShape: 'triangle' },
      { shapeType: 'pentagon', fill: 'empty', size: 'large', innerShape: 'square' },
    ],
    correctAnswer: 2,
    explanation: 'None of the three figures have an inner shape. Only choice C also has no inner shape.',
  },

  // --- Same border style (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-m-6',
    difficulty: 'medium',
    rule: 'All figures have dashed borders',
    figures: [
      { shapeType: 'circle', fill: 'empty', size: 'large', borderStyle: 'dashed' },
      { shapeType: 'square', fill: 'solid', size: 'medium', borderStyle: 'dashed' },
      { shapeType: 'triangle', fill: 'dotted', size: 'small', borderStyle: 'dashed' },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'empty', size: 'large', borderStyle: 'solid' },
      { shapeType: 'pentagon', fill: 'solid', size: 'medium', borderStyle: 'thick' },
      { shapeType: 'star', fill: 'dotted', size: 'small', borderStyle: 'thin' },
      { shapeType: 'diamond', fill: 'empty', size: 'large', borderStyle: 'dashed' },
      { shapeType: 'arrow', fill: 'solid', size: 'medium', borderStyle: 'double' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures have dashed borders. Only choice D also has a dashed border.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-7',
    difficulty: 'medium',
    rule: 'All figures have thick borders',
    figures: [
      { shapeType: 'pentagon', fill: 'solid', size: 'large', borderStyle: 'thick' },
      { shapeType: 'diamond', fill: 'empty', size: 'small', borderStyle: 'thick' },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'medium', borderStyle: 'thick' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'solid', size: 'large', borderStyle: 'thin' },
      { shapeType: 'triangle', fill: 'empty', size: 'small', borderStyle: 'dashed' },
      { shapeType: 'square', fill: 'striped-horizontal', size: 'medium', borderStyle: 'thick' },
      { shapeType: 'star', fill: 'solid', size: 'large', borderStyle: 'double' },
      { shapeType: 'cross', fill: 'empty', size: 'medium', borderStyle: 'solid' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures have thick borders. Only choice C also has a thick border.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-8',
    difficulty: 'medium',
    rule: 'All figures have thin borders',
    figures: [
      { shapeType: 'star', fill: 'empty', size: 'medium', borderStyle: 'thin' },
      { shapeType: 'arrow', fill: 'solid', size: 'large', borderStyle: 'thin' },
      { shapeType: 'cross', fill: 'striped-diagonal', size: 'small', borderStyle: 'thin' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'empty', size: 'medium', borderStyle: 'thin' },
      { shapeType: 'square', fill: 'solid', size: 'large', borderStyle: 'thick' },
      { shapeType: 'triangle', fill: 'striped-diagonal', size: 'small', borderStyle: 'dashed' },
      { shapeType: 'hexagon', fill: 'empty', size: 'medium', borderStyle: 'double' },
      { shapeType: 'pentagon', fill: 'solid', size: 'large', borderStyle: 'solid' },
    ],
    correctAnswer: 0,
    explanation: 'All three figures have thin borders. Only choice A also has a thin border.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-9',
    difficulty: 'medium',
    rule: 'All figures have double borders',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'large', borderStyle: 'double' },
      { shapeType: 'triangle', fill: 'striped-vertical', size: 'medium', borderStyle: 'double' },
      { shapeType: 'square', fill: 'empty', size: 'small', borderStyle: 'double' },
    ],
    choices: [
      { shapeType: 'pentagon', fill: 'solid', size: 'large', borderStyle: 'dashed' },
      { shapeType: 'hexagon', fill: 'striped-vertical', size: 'medium', borderStyle: 'thick' },
      { shapeType: 'diamond', fill: 'empty', size: 'small', borderStyle: 'thin' },
      { shapeType: 'star', fill: 'solid', size: 'large', borderStyle: 'solid' },
      { shapeType: 'arrow', fill: 'striped-horizontal', size: 'medium', borderStyle: 'double' },
    ],
    correctAnswer: 4,
    explanation: 'All three figures have double borders. Only choice E also has a double border.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-10',
    difficulty: 'medium',
    rule: 'All figures have solid borders',
    figures: [
      { shapeType: 'hexagon', fill: 'dotted', size: 'medium', borderStyle: 'solid' },
      { shapeType: 'star', fill: 'empty', size: 'large', borderStyle: 'solid' },
      { shapeType: 'arrow', fill: 'solid', size: 'small', borderStyle: 'solid' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'dotted', size: 'medium', borderStyle: 'dashed' },
      { shapeType: 'square', fill: 'empty', size: 'large', borderStyle: 'solid' },
      { shapeType: 'triangle', fill: 'solid', size: 'small', borderStyle: 'thick' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'medium', borderStyle: 'double' },
      { shapeType: 'diamond', fill: 'empty', size: 'large', borderStyle: 'thin' },
    ],
    correctAnswer: 1,
    explanation: 'All three figures have solid borders. Only choice B also has a solid border.',
  },

  // --- Same sides + same fill combination (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-m-11',
    difficulty: 'medium',
    rule: 'All figures are triangles AND solid',
    figures: [
      { shapeType: 'triangle', fill: 'solid', size: 'large' },
      { shapeType: 'triangle', fill: 'solid', size: 'small' },
      { shapeType: 'triangle', fill: 'solid', size: 'medium' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'empty', size: 'medium' },
      { shapeType: 'square', fill: 'solid', size: 'large' },
      { shapeType: 'triangle', fill: 'solid', size: 'large' },
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'medium' },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are solid triangles. Choice C is the only solid triangle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-12',
    difficulty: 'medium',
    rule: 'All figures are squares AND empty',
    figures: [
      { shapeType: 'square', fill: 'empty', size: 'small' },
      { shapeType: 'square', fill: 'empty', size: 'large' },
      { shapeType: 'square', fill: 'empty', size: 'medium' },
    ],
    choices: [
      { shapeType: 'square', fill: 'solid', size: 'medium' },
      { shapeType: 'diamond', fill: 'empty', size: 'large' },
      { shapeType: 'square', fill: 'striped-horizontal', size: 'small' },
      { shapeType: 'square', fill: 'empty', size: 'large' },
      { shapeType: 'circle', fill: 'empty', size: 'medium' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures are empty squares. Choice D is the only empty square.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-13',
    difficulty: 'medium',
    rule: 'All figures are hexagons AND striped',
    figures: [
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'hexagon', fill: 'striped-vertical', size: 'large' },
      { shapeType: 'hexagon', fill: 'striped-diagonal', size: 'small' },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'solid', size: 'medium' },
      { shapeType: 'pentagon', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'hexagon', fill: 'empty', size: 'small' },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'medium' },
      { shapeType: 'square', fill: 'striped-diagonal', size: 'large' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures are hexagons with stripes. Choice D is the only striped hexagon.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-14',
    difficulty: 'medium',
    rule: 'All figures are pentagons AND dotted',
    figures: [
      { shapeType: 'pentagon', fill: 'dotted', size: 'large' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'small' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'medium' },
    ],
    choices: [
      { shapeType: 'pentagon', fill: 'solid', size: 'large' },
      { shapeType: 'hexagon', fill: 'dotted', size: 'medium' },
      { shapeType: 'pentagon', fill: 'empty', size: 'small' },
      { shapeType: 'triangle', fill: 'dotted', size: 'large' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'medium' },
    ],
    correctAnswer: 4,
    explanation: 'All three figures are dotted pentagons. Choice E is the only dotted pentagon.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-15',
    difficulty: 'medium',
    rule: 'All figures are circles AND have diagonal stripes',
    figures: [
      { shapeType: 'circle', fill: 'striped-diagonal', size: 'large' },
      { shapeType: 'circle', fill: 'striped-diagonal', size: 'medium' },
      { shapeType: 'circle', fill: 'striped-diagonal', size: 'small' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'square', fill: 'striped-diagonal', size: 'medium' },
      { shapeType: 'circle', fill: 'solid', size: 'small' },
      { shapeType: 'circle', fill: 'striped-diagonal', size: 'medium' },
      { shapeType: 'hexagon', fill: 'striped-diagonal', size: 'large' },
    ],
    correctAnswer: 3,
    explanation: 'All three figures are circles with diagonal stripes. Choice D is the only circle with diagonal stripes.',
  },

  // --- Rotation patterns (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-m-16',
    difficulty: 'medium',
    rule: 'All figures are rotated 45 degrees',
    figures: [
      { shapeType: 'triangle', fill: 'solid', size: 'large', rotation: 45 },
      { shapeType: 'square', fill: 'empty', size: 'medium', rotation: 45 },
      { shapeType: 'arrow', fill: 'dotted', size: 'small', rotation: 45 },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'solid', size: 'large', rotation: 0 },
      { shapeType: 'pentagon', fill: 'empty', size: 'medium', rotation: 90 },
      { shapeType: 'star', fill: 'dotted', size: 'small', rotation: 45 },
      { shapeType: 'diamond', fill: 'solid', size: 'large', rotation: 180 },
      { shapeType: 'cross', fill: 'empty', size: 'medium', rotation: 270 },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are rotated 45 degrees. Only choice C is also rotated 45 degrees.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-17',
    difficulty: 'medium',
    rule: 'All figures are rotated 90 degrees',
    figures: [
      { shapeType: 'arrow', fill: 'solid', size: 'medium', rotation: 90 },
      { shapeType: 'triangle', fill: 'empty', size: 'large', rotation: 90 },
      { shapeType: 'cross', fill: 'striped-horizontal', size: 'small', rotation: 90 },
    ],
    choices: [
      { shapeType: 'star', fill: 'solid', size: 'medium', rotation: 0 },
      { shapeType: 'diamond', fill: 'empty', size: 'large', rotation: 90 },
      { shapeType: 'hexagon', fill: 'striped-horizontal', size: 'small', rotation: 45 },
      { shapeType: 'circle', fill: 'solid', size: 'medium', rotation: 180 },
      { shapeType: 'square', fill: 'empty', size: 'large', rotation: 270 },
    ],
    correctAnswer: 1,
    explanation: 'All three figures are rotated 90 degrees. Only choice B is also rotated 90 degrees.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-18',
    difficulty: 'medium',
    rule: 'All figures are arrows rotated to different angles',
    figures: [
      { shapeType: 'arrow', fill: 'solid', size: 'medium', rotation: 0 },
      { shapeType: 'arrow', fill: 'solid', size: 'medium', rotation: 90 },
      { shapeType: 'arrow', fill: 'solid', size: 'medium', rotation: 180 },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'solid', size: 'medium', rotation: 270 },
      { shapeType: 'arrow', fill: 'empty', size: 'medium', rotation: 270 },
      { shapeType: 'arrow', fill: 'solid', size: 'medium', rotation: 270 },
      { shapeType: 'arrow', fill: 'solid', size: 'large', rotation: 270 },
      { shapeType: 'star', fill: 'solid', size: 'medium', rotation: 270 },
    ],
    correctAnswer: 2,
    explanation: 'All three figures are solid medium arrows at different rotations. Choice C continues the pattern as a solid medium arrow at 270 degrees.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-19',
    difficulty: 'medium',
    rule: 'All figures are rotated 180 degrees',
    figures: [
      { shapeType: 'triangle', fill: 'empty', size: 'large', rotation: 180 },
      { shapeType: 'pentagon', fill: 'solid', size: 'medium', rotation: 180 },
      { shapeType: 'arrow', fill: 'dotted', size: 'small', rotation: 180 },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'empty', size: 'large', rotation: 0 },
      { shapeType: 'star', fill: 'solid', size: 'medium', rotation: 90 },
      { shapeType: 'cross', fill: 'dotted', size: 'small', rotation: 45 },
      { shapeType: 'square', fill: 'empty', size: 'large', rotation: 180 },
      { shapeType: 'diamond', fill: 'solid', size: 'medium', rotation: 270 },
    ],
    correctAnswer: 3,
    explanation: 'All three figures are rotated 180 degrees. Only choice D is also rotated 180 degrees.',
  },
  {
    type: 'figure-classification',
    id: 'fc-m-20',
    difficulty: 'medium',
    rule: 'All figures are triangles at different rotations but same fill',
    figures: [
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'medium', rotation: 0 },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'medium', rotation: 120 },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'medium', rotation: 240 },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'solid', size: 'medium', rotation: 60 },
      { shapeType: 'square', fill: 'striped-horizontal', size: 'medium', rotation: 60 },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'large', rotation: 60 },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'medium', rotation: 60 },
      { shapeType: 'triangle', fill: 'empty', size: 'medium', rotation: 60 },
    ],
    correctAnswer: 3,
    explanation: 'All three are medium triangles with horizontal stripes at different rotations. Choice D is the only medium triangle with horizontal stripes.',
  },

  // ============================================================
  // HARD QUESTIONS (fc-h-1 through fc-h-20)
  // ============================================================

  // --- Shape + fill combination (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-h-1',
    difficulty: 'hard',
    rule: 'All figures have 4+ sides AND are striped',
    figures: [
      { shapeType: 'square', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'pentagon', fill: 'striped-vertical', size: 'medium' },
      { shapeType: 'hexagon', fill: 'striped-diagonal', size: 'small' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'square', fill: 'solid', size: 'medium' },
      { shapeType: 'pentagon', fill: 'empty', size: 'small' },
      { shapeType: 'hexagon', fill: 'dotted', size: 'large' },
      { shapeType: 'diamond', fill: 'striped-vertical', size: 'medium' },
    ],
    correctAnswer: 4,
    explanation: 'All figures have 4 or more sides and are striped. Triangle (A) has only 3 sides. Choices B, C, D have the right shape but wrong fill. Only diamond with stripes (E) has 4+ sides AND stripes.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-2',
    difficulty: 'hard',
    rule: 'All figures have 5+ sides AND are solid',
    figures: [
      { shapeType: 'pentagon', fill: 'solid', size: 'large' },
      { shapeType: 'hexagon', fill: 'solid', size: 'medium' },
      { shapeType: 'pentagon', fill: 'solid', size: 'small' },
    ],
    choices: [
      { shapeType: 'square', fill: 'solid', size: 'medium' },
      { shapeType: 'hexagon', fill: 'empty', size: 'large' },
      { shapeType: 'triangle', fill: 'solid', size: 'small' },
      { shapeType: 'hexagon', fill: 'solid', size: 'medium' },
      { shapeType: 'pentagon', fill: 'striped-horizontal', size: 'large' },
    ],
    correctAnswer: 3,
    explanation: 'All figures have 5+ sides and are solid. Square (A) and triangle (C) have too few sides. Hexagon empty (B) and pentagon striped (E) have wrong fills. Only choice D (solid hexagon) matches both rules.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-3',
    difficulty: 'hard',
    rule: 'All figures have curved sides (circles) AND are dotted',
    figures: [
      { shapeType: 'circle', fill: 'dotted', size: 'large' },
      { shapeType: 'circle', fill: 'dotted', size: 'small' },
      { shapeType: 'circle', fill: 'dotted', size: 'medium' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'solid', size: 'large' },
      { shapeType: 'square', fill: 'dotted', size: 'medium' },
      { shapeType: 'circle', fill: 'empty', size: 'small' },
      { shapeType: 'triangle', fill: 'dotted', size: 'large' },
      { shapeType: 'circle', fill: 'dotted', size: 'medium' },
    ],
    correctAnswer: 4,
    explanation: 'All figures are dotted circles. The circles without dots (A, C) and the dotted non-circles (B, D) do not match. Only choice E is a dotted circle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-4',
    difficulty: 'hard',
    rule: 'All figures are empty AND have fewer than 5 sides',
    figures: [
      { shapeType: 'triangle', fill: 'empty', size: 'medium' },
      { shapeType: 'square', fill: 'empty', size: 'large' },
      { shapeType: 'diamond', fill: 'empty', size: 'small' },
    ],
    choices: [
      { shapeType: 'pentagon', fill: 'empty', size: 'medium' },
      { shapeType: 'triangle', fill: 'solid', size: 'large' },
      { shapeType: 'hexagon', fill: 'empty', size: 'small' },
      { shapeType: 'square', fill: 'empty', size: 'medium' },
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'large' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are empty and have fewer than 5 sides. Pentagon (A) and hexagon (C) have 5+ sides. Triangle solid (B) has wrong fill. Circle striped (E) has wrong fill. Only choice D (empty square) matches.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-5',
    difficulty: 'hard',
    rule: 'All figures are striped AND are not circles',
    figures: [
      { shapeType: 'star', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'diamond', fill: 'striped-vertical', size: 'medium' },
      { shapeType: 'cross', fill: 'striped-diagonal', size: 'small' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'large' },
      { shapeType: 'star', fill: 'solid', size: 'medium' },
      { shapeType: 'triangle', fill: 'striped-vertical', size: 'small' },
      { shapeType: 'hexagon', fill: 'empty', size: 'large' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'medium' },
    ],
    correctAnswer: 2,
    explanation: 'All figures are striped and none are circles. Circle (A) is excluded even with stripes. Star solid (B), hexagon empty (D), and pentagon dotted (E) lack stripes. Only choice C is a striped non-circle.',
  },

  // --- Inner shape + outer shape (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-h-6',
    difficulty: 'hard',
    rule: 'All figures have circles inside squares',
    figures: [
      { shapeType: 'square', fill: 'empty', size: 'large', innerShape: 'circle' },
      { shapeType: 'square', fill: 'solid', size: 'medium', innerShape: 'circle' },
      { shapeType: 'square', fill: 'striped-horizontal', size: 'small', innerShape: 'circle' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'empty', size: 'large', innerShape: 'square' },
      { shapeType: 'square', fill: 'empty', size: 'medium', innerShape: 'triangle' },
      { shapeType: 'triangle', fill: 'solid', size: 'small', innerShape: 'circle' },
      { shapeType: 'square', fill: 'dotted', size: 'large', innerShape: 'circle' },
      { shapeType: 'hexagon', fill: 'empty', size: 'medium', innerShape: 'circle' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are squares containing circles. Choice A has reversed shapes. Choice B has the wrong inner shape. Choice C is a triangle, not square. Choice E is a hexagon. Only choice D is a square with an inner circle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-7',
    difficulty: 'hard',
    rule: 'All figures have triangles inside circles',
    figures: [
      { shapeType: 'circle', fill: 'empty', size: 'large', innerShape: 'triangle' },
      { shapeType: 'circle', fill: 'solid', size: 'medium', innerShape: 'triangle' },
      { shapeType: 'circle', fill: 'dotted', size: 'small', innerShape: 'triangle' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'empty', size: 'large', innerShape: 'circle' },
      { shapeType: 'circle', fill: 'empty', size: 'medium', innerShape: 'square' },
      { shapeType: 'square', fill: 'solid', size: 'small', innerShape: 'triangle' },
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'large', innerShape: 'dot' },
      { shapeType: 'circle', fill: 'striped-vertical', size: 'medium', innerShape: 'triangle' },
    ],
    correctAnswer: 4,
    explanation: 'All figures are circles containing triangles. Choice A reverses the shapes. Choice B has the wrong inner shape. Choice C is a square. Choice D has a dot. Only choice E is a circle with an inner triangle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-8',
    difficulty: 'hard',
    rule: 'All figures have dots inside hexagons',
    figures: [
      { shapeType: 'hexagon', fill: 'empty', size: 'large', innerShape: 'dot' },
      { shapeType: 'hexagon', fill: 'solid', size: 'medium', innerShape: 'dot' },
      { shapeType: 'hexagon', fill: 'striped-diagonal', size: 'small', innerShape: 'dot' },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'empty', size: 'medium', innerShape: 'circle' },
      { shapeType: 'pentagon', fill: 'solid', size: 'large', innerShape: 'dot' },
      { shapeType: 'hexagon', fill: 'dotted', size: 'medium', innerShape: 'dot' },
      { shapeType: 'square', fill: 'empty', size: 'small', innerShape: 'dot' },
      { shapeType: 'hexagon', fill: 'solid', size: 'large', innerShape: 'triangle' },
    ],
    correctAnswer: 2,
    explanation: 'All figures are hexagons with inner dots. Choice A has an inner circle. Choice B is a pentagon. Choice D is a square. Choice E has inner triangle. Only choice C is a hexagon with a dot.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-9',
    difficulty: 'hard',
    rule: 'All figures have stars inside pentagons',
    figures: [
      { shapeType: 'pentagon', fill: 'empty', size: 'large', innerShape: 'star' },
      { shapeType: 'pentagon', fill: 'solid', size: 'medium', innerShape: 'star' },
      { shapeType: 'pentagon', fill: 'striped-horizontal', size: 'small', innerShape: 'star' },
    ],
    choices: [
      { shapeType: 'star', fill: 'empty', size: 'large', innerShape: 'pentagon' },
      { shapeType: 'pentagon', fill: 'empty', size: 'medium', innerShape: 'circle' },
      { shapeType: 'hexagon', fill: 'solid', size: 'small', innerShape: 'star' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'large', innerShape: 'star' },
      { shapeType: 'pentagon', fill: 'solid', size: 'medium', innerShape: 'dot' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are pentagons containing stars. Choice A reverses the shapes. Choices B and E have wrong inner shapes. Choice C is a hexagon. Only choice D is a pentagon with an inner star.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-10',
    difficulty: 'hard',
    rule: 'All figures have squares inside diamonds',
    figures: [
      { shapeType: 'diamond', fill: 'empty', size: 'large', innerShape: 'square' },
      { shapeType: 'diamond', fill: 'striped-vertical', size: 'medium', innerShape: 'square' },
      { shapeType: 'diamond', fill: 'solid', size: 'small', innerShape: 'square' },
    ],
    choices: [
      { shapeType: 'square', fill: 'empty', size: 'large', innerShape: 'diamond' },
      { shapeType: 'diamond', fill: 'empty', size: 'medium', innerShape: 'triangle' },
      { shapeType: 'triangle', fill: 'striped-vertical', size: 'small', innerShape: 'square' },
      { shapeType: 'diamond', fill: 'dotted', size: 'large', innerShape: 'square' },
      { shapeType: 'hexagon', fill: 'solid', size: 'medium', innerShape: 'square' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are diamonds containing squares. Choice A reverses the shapes. Choices B has wrong inner shape. Choice C is a triangle. Choice E is a hexagon. Only choice D is a diamond with an inner square.',
  },

  // --- Count + shape (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-h-11',
    difficulty: 'hard',
    rule: 'All figures contain exactly 2 shapes',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'medium', count: 2 },
      { shapeType: 'triangle', fill: 'empty', size: 'large', count: 2 },
      { shapeType: 'square', fill: 'dotted', size: 'small', count: 2 },
    ],
    choices: [
      { shapeType: 'pentagon', fill: 'solid', size: 'medium', count: 1 },
      { shapeType: 'hexagon', fill: 'empty', size: 'large', count: 3 },
      { shapeType: 'diamond', fill: 'dotted', size: 'small', count: 2 },
      { shapeType: 'star', fill: 'solid', size: 'medium', count: 4 },
      { shapeType: 'arrow', fill: 'empty', size: 'large', count: 1 },
    ],
    correctAnswer: 2,
    explanation: 'All figures contain exactly 2 shapes. Only choice C also has a count of 2.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-12',
    difficulty: 'hard',
    rule: 'All figures contain exactly 3 circles',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'small', count: 3 },
      { shapeType: 'circle', fill: 'empty', size: 'medium', count: 3 },
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'large', count: 3 },
    ],
    choices: [
      { shapeType: 'circle', fill: 'solid', size: 'medium', count: 2 },
      { shapeType: 'square', fill: 'empty', size: 'large', count: 3 },
      { shapeType: 'circle', fill: 'dotted', size: 'small', count: 3 },
      { shapeType: 'circle', fill: 'solid', size: 'medium', count: 4 },
      { shapeType: 'triangle', fill: 'solid', size: 'large', count: 3 },
    ],
    correctAnswer: 2,
    explanation: 'All figures have exactly 3 circles. Choice A has only 2 circles. Choice B has 3 squares, not circles. Choice D has 4 circles. Choice E has triangles. Only choice C has 3 circles.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-13',
    difficulty: 'hard',
    rule: 'All figures contain exactly 1 triangle',
    figures: [
      { shapeType: 'triangle', fill: 'solid', size: 'large', count: 1 },
      { shapeType: 'triangle', fill: 'empty', size: 'small', count: 1 },
      { shapeType: 'triangle', fill: 'striped-vertical', size: 'medium', count: 1 },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'solid', size: 'medium', count: 2 },
      { shapeType: 'square', fill: 'empty', size: 'large', count: 1 },
      { shapeType: 'triangle', fill: 'dotted', size: 'small', count: 3 },
      { shapeType: 'circle', fill: 'solid', size: 'medium', count: 1 },
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'large', count: 1 },
    ],
    correctAnswer: 4,
    explanation: 'All figures have exactly 1 triangle. Choice A has 2. Choice B is a square. Choice C has 3. Choice D is a circle. Only choice E has exactly 1 triangle.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-14',
    difficulty: 'hard',
    rule: 'All figures contain exactly 4 stars',
    figures: [
      { shapeType: 'star', fill: 'solid', size: 'small', count: 4 },
      { shapeType: 'star', fill: 'empty', size: 'medium', count: 4 },
      { shapeType: 'star', fill: 'dotted', size: 'large', count: 4 },
    ],
    choices: [
      { shapeType: 'star', fill: 'solid', size: 'medium', count: 3 },
      { shapeType: 'star', fill: 'striped-horizontal', size: 'large', count: 4 },
      { shapeType: 'diamond', fill: 'solid', size: 'small', count: 4 },
      { shapeType: 'star', fill: 'empty', size: 'medium', count: 5 },
      { shapeType: 'cross', fill: 'dotted', size: 'large', count: 4 },
    ],
    correctAnswer: 1,
    explanation: 'All figures have exactly 4 stars. Choice A has 3 stars. Choice C has diamonds. Choice D has 5 stars. Choice E has crosses. Only choice B has exactly 4 stars.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-15',
    difficulty: 'hard',
    rule: 'All figures contain exactly 2 solid squares',
    figures: [
      { shapeType: 'square', fill: 'solid', size: 'large', count: 2 },
      { shapeType: 'square', fill: 'solid', size: 'medium', count: 2 },
      { shapeType: 'square', fill: 'solid', size: 'small', count: 2 },
    ],
    choices: [
      { shapeType: 'square', fill: 'empty', size: 'medium', count: 2 },
      { shapeType: 'square', fill: 'solid', size: 'large', count: 3 },
      { shapeType: 'triangle', fill: 'solid', size: 'medium', count: 2 },
      { shapeType: 'square', fill: 'solid', size: 'small', count: 1 },
      { shapeType: 'square', fill: 'solid', size: 'medium', count: 2 },
    ],
    correctAnswer: 4,
    explanation: 'All figures have exactly 2 solid squares. Choice A is empty. Choice B has 3. Choice C has triangles. Choice D has only 1. Only choice E has exactly 2 solid squares.',
  },

  // --- Three properties combined (5 questions) ---
  {
    type: 'figure-classification',
    id: 'fc-h-16',
    difficulty: 'hard',
    rule: 'All figures are large, solid, and have an inner dot',
    figures: [
      { shapeType: 'circle', fill: 'solid', size: 'large', innerShape: 'dot' },
      { shapeType: 'square', fill: 'solid', size: 'large', innerShape: 'dot' },
      { shapeType: 'hexagon', fill: 'solid', size: 'large', innerShape: 'dot' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'solid', size: 'large', innerShape: 'circle' },
      { shapeType: 'pentagon', fill: 'empty', size: 'large', innerShape: 'dot' },
      { shapeType: 'diamond', fill: 'solid', size: 'small', innerShape: 'dot' },
      { shapeType: 'star', fill: 'solid', size: 'large', innerShape: 'dot' },
      { shapeType: 'cross', fill: 'solid', size: 'large', innerShape: 'none' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are large, solid, and have an inner dot. Choice A has inner circle. Choice B is empty. Choice C is small. Choice E has no inner shape. Only choice D matches all three properties.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-17',
    difficulty: 'hard',
    rule: 'All figures are medium, empty, and have dashed borders',
    figures: [
      { shapeType: 'triangle', fill: 'empty', size: 'medium', borderStyle: 'dashed' },
      { shapeType: 'pentagon', fill: 'empty', size: 'medium', borderStyle: 'dashed' },
      { shapeType: 'star', fill: 'empty', size: 'medium', borderStyle: 'dashed' },
    ],
    choices: [
      { shapeType: 'circle', fill: 'empty', size: 'large', borderStyle: 'dashed' },
      { shapeType: 'square', fill: 'solid', size: 'medium', borderStyle: 'dashed' },
      { shapeType: 'hexagon', fill: 'empty', size: 'medium', borderStyle: 'thick' },
      { shapeType: 'diamond', fill: 'empty', size: 'medium', borderStyle: 'dashed' },
      { shapeType: 'arrow', fill: 'empty', size: 'medium', borderStyle: 'solid' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are medium, empty, with dashed borders. Choice A is large. Choice B is solid. Choice C has thick border. Choice E has solid border. Only choice D matches all three.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-18',
    difficulty: 'hard',
    rule: 'All figures are small, striped, and have thick borders',
    figures: [
      { shapeType: 'circle', fill: 'striped-horizontal', size: 'small', borderStyle: 'thick' },
      { shapeType: 'diamond', fill: 'striped-vertical', size: 'small', borderStyle: 'thick' },
      { shapeType: 'arrow', fill: 'striped-diagonal', size: 'small', borderStyle: 'thick' },
    ],
    choices: [
      { shapeType: 'triangle', fill: 'striped-horizontal', size: 'large', borderStyle: 'thick' },
      { shapeType: 'square', fill: 'solid', size: 'small', borderStyle: 'thick' },
      { shapeType: 'pentagon', fill: 'striped-vertical', size: 'small', borderStyle: 'dashed' },
      { shapeType: 'hexagon', fill: 'striped-diagonal', size: 'small', borderStyle: 'thick' },
      { shapeType: 'star', fill: 'striped-horizontal', size: 'small', borderStyle: 'thin' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are small, striped, with thick borders. Choice A is large. Choice B is solid. Choice C has dashed border. Choice E has thin border. Only choice D matches all three.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-19',
    difficulty: 'hard',
    rule: 'All figures are rotated 45 degrees, dotted, and contain an inner circle',
    figures: [
      { shapeType: 'square', fill: 'dotted', size: 'large', rotation: 45, innerShape: 'circle' },
      { shapeType: 'triangle', fill: 'dotted', size: 'medium', rotation: 45, innerShape: 'circle' },
      { shapeType: 'pentagon', fill: 'dotted', size: 'small', rotation: 45, innerShape: 'circle' },
    ],
    choices: [
      { shapeType: 'hexagon', fill: 'dotted', size: 'large', rotation: 0, innerShape: 'circle' },
      { shapeType: 'diamond', fill: 'solid', size: 'medium', rotation: 45, innerShape: 'circle' },
      { shapeType: 'star', fill: 'dotted', size: 'small', rotation: 45, innerShape: 'dot' },
      { shapeType: 'arrow', fill: 'dotted', size: 'large', rotation: 45, innerShape: 'circle' },
      { shapeType: 'cross', fill: 'dotted', size: 'medium', rotation: 45, innerShape: 'square' },
    ],
    correctAnswer: 3,
    explanation: 'All figures are rotated 45 degrees, dotted, and have an inner circle. Choice A is not rotated. Choice B is solid. Choice C has inner dot. Choice E has inner square. Only choice D matches all three.',
  },
  {
    type: 'figure-classification',
    id: 'fc-h-20',
    difficulty: 'hard',
    rule: 'All figures have count of 2, are empty, and have double borders',
    figures: [
      { shapeType: 'circle', fill: 'empty', size: 'large', borderStyle: 'double', count: 2 },
      { shapeType: 'triangle', fill: 'empty', size: 'medium', borderStyle: 'double', count: 2 },
      { shapeType: 'hexagon', fill: 'empty', size: 'small', borderStyle: 'double', count: 2 },
    ],
    choices: [
      { shapeType: 'square', fill: 'solid', size: 'medium', borderStyle: 'double', count: 2 },
      { shapeType: 'pentagon', fill: 'empty', size: 'large', borderStyle: 'dashed', count: 2 },
      { shapeType: 'diamond', fill: 'empty', size: 'small', borderStyle: 'double', count: 3 },
      { shapeType: 'star', fill: 'empty', size: 'medium', borderStyle: 'double', count: 2 },
      { shapeType: 'arrow', fill: 'empty', size: 'large', borderStyle: 'double', count: 1 },
    ],
    correctAnswer: 3,
    explanation: 'All figures have count 2, are empty, and have double borders. Choice A is solid. Choice B has dashed border. Choice C has count 3. Choice E has count 1. Only choice D matches all three.',
  },
];
